# Dependency Manager (Dependabot)

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    
    schedule:
      interval: "weekly"
      time: "16:00"
      timezone: "Europe/Berlin"
    
    assignees:
      - "Neonsy"
    
    # reviewers:
    #   - "Neonsy"
    
    labels:
      - "dependabot"
      - "dependencies"
      - "nodejs"
    
    versioning-strategy: "increase"
    target-branch: "main"

    groups:
      prettier:
        dependency-type: "development"
        patterns:
          - "*prettier*"

  - package-ecosystem: "composer"
    directory: "/"
    
    schedule:
      interval: "weekly"
      time: "16:00"
      timezone: "Europe/Berlin"
    
    assignees:
      - "Neonsy"
    
    labels:
      - "composer"
      - "dependabot"
      - "dependencies"
      - "php"
    
    versioning-strategy: "increase"
    target-branch: "main"
